[package]
name = "decay"
version = "0.1.0"
description = "Game Engine using Vulkan"
authors = ["Daniel Whelan <chobomuffin@gmail.com>", "Shervin Aflatooni <shervinaflatooni@gmail.com>"]
license = "MIT"
repository = "https://github.com/chobomuffin/decay"

[dependencies]
